apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: devops-app-alerts
  namespace: monitoring
  labels:
    release: monitoring
spec:
  groups:
    - name: devops-app.rules
      rules:
        - alert: DevopsAppDown
          expr: up{job="devops-app"} == 0
          for: 2m
          labels:
            severity: critical
          annotations:
            summary: "devops-app is down"

        - alert: HighErrorRate
          expr: |
            sum(rate(flask_http_request_total{status=~"5.."}[5m]))
              / sum(rate(flask_http_request_total[5m])) > 0.05
          for: 5m
          labels:
            severity: warning
          annotations:
            summary: "High 5xx error rate"

        - alert: PodRestartingTooMuch
          expr: increase(kube_pod_container_status_restarts_total{namespace="default"}[15m]) > 3
          for: 5m
          labels:
            severity: warning
          annotations:
            summary: "Pod {{ $labels.pod }} keeps restarting"
