grafana:
  enabled: true
  adminPassword: "admin123"
  service:
    type: NodePort

prometheus:
  service:
    type: NodePort
  prometheusSpec:
    retention: 7d

alertmanager:
  service:
    type: NodePort
  config:
    route:
      receiver: discord
    receivers:
      - name: discord
        webhook_configs:
          - url: "https://discord.com/api/webhooks/1494365933014089849/YL6Ca9xKIS6cNuDWzOkj1Q_7-4YxxvWNWM3Op8jeXH7vqc3_XE--kHbUcLsHtWqeSAM-"
