grafana:
  enabled: true
  adminPassword: "admin123"
  service:
    type: NodePort

prometheus:
  service:
    type: NodePort
  prometheusSpec:
    retention: 7d

alertmanager:
  service:
    type: NodePort
  config:
    route:
      receiver: discord
    receivers:
      - name: discord
        webhook_configs:
          - url: "REPLACE_WITH_DISCORD_WEBHOOK_URL"
